### ISSUE TITLE
demo fails

### ISSUE THREAD

**Issue by rcemper** [SergeyMi37/appmsw-banks-ru#1]
How to Test it
Open link: http://localhost:52663/apptoolsrest/a/info&class=appmsw-banks-ru

{
	"errors":[ {
			"code":5002,
			"domain":"%ObjectErrors",
			"error":"ERROR #5002: ObjectScript error: <CLASS DOES NOT EXIST>zGetMain+16^apptools.lte.adminStatic.1 *User.appmsw-banks-ru",
			"id":"ObjectScriptError",
			"params":["<CLASS DOES NOT EXIST>zGetMain+16^apptools.lte.adminStatic.1 *User.appmsw-banks-ru"
			]
		}
	],
	"summary":"ERROR #5002: ObjectScript error: <CLASS DOES NOT EXIST>zGetMain+16^apptools.lte.adminStatic.1 *User.appmsw-banks-ru"
}

**Comment by SergeyMi37** [comment]
Fixed readme
http://localhost:52663/apptoolsrest/a/info&class=appmsw-banks-ru&namespace=user

**Comment by SergeyMi37** [comment]
Thanks, Robert.
