### ISSUE TITLE
#1 is not fixed 

### ISSUE THREAD

**Issue by rcemper** [SergeyMi37/appmsw-banks-ru#3]
http://localhost:52663/apptoolsrest/a/info&class=appmsw-banks-ru&namespace=user
returns:
{
	"errors":[ {
			"code":5002,
			"domain":"%ObjectErrors",
			"error":"**ERROR #5002: ObjectScript error: <CLASS DOES NOT EXIST>zGetMain+16^apptools.lte.adminStatic.1 *User.appmsw-banks-ru",**
			"id":"ObjectScriptError",
			"params":["**<CLASS DOES NOT EXIST>**zGetMain+16^apptools.lte.adminStatic.1 ***User.appmsw-banks-ru**"
			]
		}
	],
	"summary":"ERROR #5002: ObjectScript error: <CLASS DOES NOT EXIST>zGetMain+16^apptools.lte.adminStatic.1 *User.appmsw-banks-ru"
}

looking into /src/cls/appmsw/banks/ hte is nothing related to find
Sorry.

**Comment by SergeyMi37** [comment]
I understood my mistake. Thanks Robert
http://localhost:52663/apptoolsrest/a/info&class=appmsw.banks.info&namespace=user
Thanks Robert
